spring.application.name=demo
# for https
server.forward-headers-strategy=framework

application.security.jwt.secret-key=Q0lqV0NQd0dXR1Zy1KZkV2Q0xrR1NyV3d1aDVMNlRkT0drZm1wUVJWeVE=

spring.datasource.url=jdbc:mysql://localhost:3306/assetarc?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=thilak05

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true